# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0bb79837ba2498669cadf6f39cdb0566d3da15545a9044b053e65a13dcc71ec85dbd8a92c327b196e85072a90bb7eff9cd52afde6a652a967874fb99effe3d4

test:
  secret_key_base: 32aa75aa350ae1d57f319b6eb7a98788fc2898ce1c632ff06ba42d10293df1c5b1a9b5a2b2038ed8eb28afee916ff14dc29b3b4ea220caa8928c134ae5911189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
